my_project_appartoo_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: MyProjectAppartooUserBundle:Default:index }
user_logout:
       pattern:   /logout
user_registerr:
       pattern:   /register
