my_project_appartoo_user:
    resource: "@MyProjectAppartooUserBundle/Resources/config/routing.yml"
    prefix:   /

my_project_appartoo_repertoire:
    resource: "@MyProjectAppartooRepertoireBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin